name = "authhero-proxy"
main = "src/index.ts"
compatibility_date = "2025-05-23"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "proxy.authhe.ro", custom_domain = true }
]

[observability]
enabled = true